### ISSUE TITLE
Arrays practice

### ISSUE THREAD

**Issue by atherdon** [vadim9999/js#2]
Посмотри на эти разные массивы которые я для тебя выбрал.
кратко опиши каждый, как ты его понимаешь.
Еще важно будет уточнять, что именно ты не понял
1) https://github.com/GroceriStar/static-data/blob/master/dist/data/simple/cuisines.js
2) https://github.com/GroceriStar/static-data/blob/master/dist/data/simple/sample-ing.js
3) https://github.com/GroceriStar/static-data/blob/master/dist/data/simple/Ingredients3/Ingredients.js
4) https://github.com/GroceriStar/static-data/blob/master/dist/data/simple/Ingredients4/Ingredients.js
5) https://github.com/GroceriStar/static-data/blob/master/dist/data/simple/Menu/Menu.js
6) https://github.com/GroceriStar/static-data/blob/master/dist/data/simple/Nutritions/nutritions.js
7) https://github.com/GroceriStar/static-data/blob/master/dist/data/simple/Recipe/recipes.js
8) https://github.com/GroceriStar/static-data/blob/master/dist/data/simple/Recipe3/Recipe.js#L49

**Comment by vadim9999** [comment]
1) Объявлен одномерный масив строк (кулинарные кухни стран). export default cuisines; означает что в другом скрипте с помощью import можно получить значение или вызвать функцию.
2) Объявлен массив ingredients. В каждом елементе массива находится объект(он обозначается фигурными скобами), в котором есть свойства. Эти свойства выглядят так 
name: "Sirius"
name - это имя свойства,
"Sirius" - значение этого свойства
для получения элемента с массива ingredients[0].name
Также в свойстве может находится другой объект. Похоже на json.
3) массив не отличается от второго
4) я вот немного не понял get это функция и переменная одновременно?
то есть var arr = get(departments);
departments - это одномерный массив объектов
var data = get;
уже в data записуется массив.
5) В каждом объекте одномерного массива nutritions находится свойство date : new Date(). new Date() создаё новый "объект" который возвращает текущую дату и время в виде строки.
6)  Объявлен одномерный массив nutritions. В качестве имени свойства объекта используется строчный литерал. Также присутствует в свойстве "vitamins" ещё один объект со свойствами "а" и "с"
для получение данных 
nutritions[0]["calories"]
nutritions[0]["vitamins"]["a"]
7) Массив data включает в себя несколько объектов. В каждом объекте есть свойства title строковое значение,  directions имеет массив строк.
8) Одномерный массив allergies_one в котором используется объект results со свойствами allergies, courses и тд. в этих свойствах значения или массив или объект.
var results = {courses:[0,2,34,3]};
var results2 = {
  courses:{
  0:3,
  1:4
}};
console.log(results.courses[1]);
console.log(results2.courses[0]);

**Comment by atherdon** [comment]
@vadim9999 шикарно!
4. `get` это функция/метод. в этой строке `var arr=get(departments);` просиходит следующее -
фукнция `get` возвращает массив и мы его сразу запихиваем в переменную arr(сокращенно array) - не самое хорошее название, но я спешил

можешь переходить к циклам. дальше будет интересное практическое задание, связанное с кодом проекта
